### ISSUE TITLE
Error: Recieved null result from API

### ISSUE THREAD

**Issue by phpoms** [brucealdridge/VendAPI#20]
I am trying to use your updated library for OAuth2.0 But it seems that it doesn't fetch records. I am trying to use it with Personal Token instead of OAuth2.0 Token. 

I feel it though error while trying to use/fetch product list using. my code looks like this

include 'src/VendAPI/VendAPI.php';
$vendapi = new VendAPI\VendAPI('https://shopname.vendhq.com','Bearer','my personal token');
vendapi->getProducts()

**Comment by downunder18** [comment]
I am having the same issue, any insight help with this would be greatly appreciated.Thanks

**Comment by iamswain** [comment]
Having the same issue, this is the error we get returned:

```
Fatal error: Uncaught exception 'VendAPI\Exception' with message 'Error: Recieved null result from API' in /../VendAPI/VendAPI.php:273 Stack trace: #0 /../VendAPI/VendAPI.php(179): VendAPI\VendAPI->_request('/api/products') #1 /kunden/463252_64283/../VendAPI/VendAPI.php(101): VendAPI\VendAPI->apiGetProducts('') #2 /../sync.php(658): VendAPI\VendAPI->getProducts() #3 {main} thrown in /../VendAPI/VendAPI.php on line 273
```

**Comment by chilles1** [comment]
Good to know that I'm not alone! Got the same error.
I tried the same as phpoms to test it. The token is correct because i got a response with
https://[account].vendhq.com/api/products?access_token=[token]

**Comment by chilles1** [comment]
The bug is in VendRequest.php

Replace this line:
CURLOPT_HTTPHEADER,array(

with this one:
CURLOPT_HTTPHEADER => array(

If you have a valid token it should work.

**Comment by phpoms** [comment]
Yess, it works. Thanks So much

**Comment by brucealdridge** [comment]
thanks @chilles1
