### ISSUE TITLE
More explicit pagination options

### ISSUE THREAD

**Issue by joeswann** [brucealdridge/VendAPI#22]
Currently trying to sync a huge number of products and it's overwhelming a 512MB allocated memory limit.

It would be nice if there was a way to handle pagination explicitly to reduce the memory overhead, I'm going to fork and add a basic solution in for now.. But it won't be beautiful.

**Comment by brucealdridge** [comment]
search for automatic_depage .. it automatically joins the resultset together which is handy for small batches, for larger ones its a bit of a headache,

**Comment by joeswann** [comment]
Haha yes, that is what I am finding.
