### ISSUE TITLE
SemVer and releases

### ISSUE THREAD

**Issue by dmnc** [brucealdridge/VendAPI#29]
It would be great to get a new release to include the most recent changes and use [SemVer](http://semver.org/) to keep releases going forward. This would make the next release v1.5.1.

Without this a developer has to a lot of messing around in their composer.json to get anything beyond v1.5 if the dependency tree is at all complex because dev-master is seen as unstable.

**Comment by bendubuisson** [comment]
+1

**Comment by brucealdridge** [comment]
Submit a PR, those are easy to approve 😀

**Comment by bendubuisson** [comment]
I think we're just asking you for a new release :)

**Comment by brucealdridge** [comment]
done.

**Comment by bendubuisson** [comment]
awesome thanks for the hard work @brucealdridge ! 🎉
