### ISSUE TITLE
v1.5.2 not in Packagist

### ISSUE THREAD

**Issue by TomCawthorn** [brucealdridge/VendAPI#32]
Hey @brucealdridge,

The latest release isn't showing up on Packagist

https://packagist.org/packages/vendapi/vendapi#dev-master

Is there something you can do to nudge it along?

Thanks,

Tom

**Comment by TomCawthorn** [comment]
I think there's a handy 'update' button next to the package in packagist that needs hitting

**Comment by brucealdridge** [comment]
done
